//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepDesktop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flooor2ForMessage
    {
        public int Id { get; set; }
        public int MessageId { get; set; }
        public Nullable<bool> Light { get; set; }
    
        public virtual Message Message { get; set; }
    }
}
