//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepDesktop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Message()
        {
            this.Flooor2ForMessage = new HashSet<Flooor2ForMessage>();
            this.Floor1ForMessage = new HashSet<Floor1ForMessage>();
            this.Floor3forMessage = new HashSet<Floor3forMessage>();
            this.Flor4ForMessage = new HashSet<Flor4ForMessage>();
            this.WindowsForRoom = new HashSet<WindowsForRoom>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Date { get; set; }
        public Nullable<int> RoomsCount { get; set; }
        public string DateDescription { get; set; }
        public string RoomsCountDescription { get; set; }
        public string WindowsDescriptiono { get; set; }
        public string WindowsForRoomDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flooor2ForMessage> Flooor2ForMessage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Floor1ForMessage> Floor1ForMessage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Floor3forMessage> Floor3forMessage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flor4ForMessage> Flor4ForMessage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WindowsForRoom> WindowsForRoom { get; set; }
    }
}
